spring.application.name=shopkart

spring.datasource.url=jdbc:mysql://localhost:3306/shopkart_db
spring.datasource.username=root
spring.datasource.password=adhi

spring.jpa.hibernate.ddl-auto=update

cloudinary.cloud-name=c2qlbaw9
cloudinary.api-key=156452163828135
cloudinary.api-secret=-e-KMP8LA-utblPHhk8oJsfL3UE